mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('posts/', include('posts.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name = 'posts'
urlpatterns = [
    # ex: /polls/
    path('', views.IndexView.as_view(), name='index'),
    # ex: /polls/5/
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    # ex: /polls/profile
    path('profile', views.UserPostsView.as_view(), name='profile'),
    # ex: /polls/5/results/
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    
    path('likepost', views.LikePost, name="like"),
    path('commentpost', views.CommentPost, name="comment")
 
] 

posts/models.py
import datetime
from PIL import Image
from django.db import models
from django.utils import timezone
from django.contrib import admin
from django.contrib.auth.models import User
     
from django.contrib.auth.models import AbstractUser
from django.utils.html import mark_safe

class CustomUser(AbstractUser):
    profile_pic = models.ImageField(upload_to = 'profile_pictures')

class Post(models.Model):
    owner = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, null=True, blank=True)
    media_path = models.ImageField(upload_to = 'post_pictures')
    media_desc = models.CharField(max_length=200, default="")
    pub_date = models.DateTimeField('date published')
    likes = models.ManyToManyField(CustomUser, related_name="likes", through='PostLikes')
    
    def __str__(self):
        return self.media_path.url
 
    @admin.display(
        boolean=True,
        ordering='pub_date',
        description='Published recently?',
    )
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now


class Comment(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    comment_text = models.CharField(max_length=200)
        
    def __str__(self):
        return self.comment_text

class PostLikes(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)

posts/views.py
from django.http import HttpResponse, HttpResponseRedirect
import json
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.db.models import Count, Exists, OuterRef
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Comment, Post, PostLikes


@login_required
def results(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    return render(request, 'posts/results.html', {'post': post})

class IndexView(LoginRequiredMixin,generic.ListView):
    template_name = 'posts/index.html'
    context_object_name = 'latest_post_list'

    def get_queryset(self):
        """Return the last five published questions."""
            
        return Post.objects.filter(
                pub_date__lte = timezone.now()
            ).annotate(num_likes=Count('likes', distinct=True)
            ).annotate(num_comments=Count('comment', distinct=True)
            ).annotate(is_liked=Exists(PostLikes.objects.filter(user=self.request.user,post_id=OuterRef('pk')))
            ).order_by('-pub_date')[:5]

class DetailView(LoginRequiredMixin,generic.DetailView):
    model = Post
    template_name = 'posts/detail.html'
    
    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Post.objects.filter(pub_date__lte=timezone.now())

class UserPostsView(LoginRequiredMixin,generic.ListView):
    template_name = 'posts/index.html'
    context_object_name = 'latest_post_list'
    
    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Post.objects.filter(pub_date__lte=timezone.now()).filter(owner = self.request.user).order_by('-pub_date')


class ResultsView(LoginRequiredMixin,generic.DetailView):
    model = Post
    template_name = 'posts/results.html'
    
    def get_queryset(self):
        return Post.objects.filter(
                pub_date__lte = timezone.now()
            ).annotate(num_likes=Count('likes')
            ).annotate(is_liked=Exists(PostLikes.objects.filter(user=self.request.user,post_id=OuterRef('pk'))))

"""
def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/index.html', context)

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})
    
def vote(request, question_id):
    return HttpResponse("You're voting on question %s." % question_id)
"""

@login_required
def LikePost(request):
    post = get_object_or_404(Post, pk=request.POST['post_id'])
    
    is_liked = False
    if post.likes.filter(id=request.user.id).exists():
        post.likes.remove(request.user)
        is_liked = False
    else:
        post.likes.add(request.user)
        is_liked= True
    
    dict = {'like_count':post.likes.count(), 'is_liked':is_liked}
    return HttpResponse(json.dumps(dict), content_type='application/json')

    
@login_required
def CommentPost(request):
    post = get_object_or_404(Post, pk=request.POST['post_id'])
    
    b = Comment(user=request.user, post=post, comment_text=request.POST['comment'])
    b.save()
    # post.comment.add(b)
    
    dict = {'success':True, 'Comment':"successful"}
    return HttpResponse(json.dumps(dict), content_type='application/json')

posts/templates/posts/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Social{% endblock %}</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" type="text/css" href="{% static 'posts/style.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
</head>

<script>
    $(document).ready(function(){
        $(".like-button").click(function(){
          var clickedLikeButton = $(this);
          $.post("{% url 'posts:like'%}",
          {
            post_id : clickedLikeButton.val(),
            csrfmiddlewaretoken: '{{ csrf_token }}'
          },
          function(data,status){
            if(data.is_liked){
              if(!clickedLikeButton.hasClass("liked"))
              {
                clickedLikeButton.addClass("liked");
                clickedLikeButton.html("favorite")
              }
            }
            else{
              if(clickedLikeButton.hasClass("liked"))
              {
                clickedLikeButton.removeClass("liked");
                clickedLikeButton.html("favorite_border")
              }
            }
            $('#'+clickedLikeButton.val()).html( + data.like_count + ' likes');
          });
        });
    
        
        $("#comment-send").click(function(){
            var clickedButton = $(this);
            clickedButton.prop('disabled', true)
          
            $.post("{% url 'posts:comment'%}",
            {
              post_id : clickedButton.val(),
              comment : $(".comment-input").val(),
              csrfmiddlewaretoken: '{{ csrf_token }}'
            },
            function(data,status){
              if(data.success)
              {
                location.reload();
              }
              else
              {
                clickedButton.prop('disabled', false)
              }
            });
        });
    });
</script>
<body>
    <div id="topbar">
        {% block topbar %}
        <ul class="topbar-nav">
            {% if user.is_authenticated %}
            <li><img class="profile-pic" src="{{ MEDIA_URL }}{{ user.profile_pic.url }}">
                <span>@{{ user.get_username }}</span></li>
            <li><a style="color: red; font-weight: bold;" href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>
            {% else %}
            <li><a  style="color: rgb(0, 162, 255); font-weight: bold;" href="{% url 'login'%}?next={{request.path}}">Login</a></li>
            {% endif %}
           
        </ul>
        {% endblock %}
    </div>
 
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

posts/templates/posts/base_post.html
{% load static %}
<div class="post">
    <div class="header">
        {% block header %}
        <img class="profile-pic" src="{{ MEDIA_URL }}{{post.owner.profile_pic.url}}">
        <strong>
          @{{ post.owner }}
        </strong>
        {% endblock header %}
    </div>
   
    <div class="media">
        {% block media %}
            <img src="{{ MEDIA_URL }}{{post.media_path.url}}" alt="My image">
        {% endblock media %}
    </div>
    
    <div class="bottom">
      <div class="buttons">
        <div class="buttons-left">
            {% block buttons-left %}
                {% if post.is_liked %} 
                <button value="{{post.id}}" class="like-button material-icons liked">
                  favorite
                </button>
                {% else %}
                <button value="{{post.id}}" class="like-button material-icons">
                  favorite_border
                </button>
                {% endif %}
            
                
            {% endblock buttons-left %}
        </div>
        <div class="buttons-right">
            {% block buttons-right %}
                <span class="material-icons">
                  bookmark_border
                </span>
            {% endblock buttons-right %}
        </div>
    </div>
      
    {% block precomment-section %}
        <strong id={{post.id}}>{{ post.num_likes }} likes</strong>
    {% endblock precomment-section %}

    {% block description %}
        <p class="comment" ><strong>@{{ post.owner }}</strong>{{post.media_desc}}</p>
    {% endblock description%}

    <div class="comments">
        {% block comments %}
        <ul>
            {% for comment in post.comment_set.all %}
            <li>
                <img class="profile-pic" src="{{ MEDIA_URL }}{{comment.user.profile_pic.url}}">
                <p class="comment"><strong>@{{comment.user}}</strong>{{ comment.comment_text }}</p>
            </li>
            {% endfor %}
        </ul>
        {% endblock comments %}
    </div>

    {% block postcomment-section %}
    <div class="comment-section">
        <input type="text" name="" id="" class="comment-input">
        <button id="comment-send" value="{{post.id}}">Send</button>
    </div>
    {% endblock postcomment-section %}
    
</div>
</div> 

posts/templates/posts/detail.html
<!--

    <form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ question.question_text }}</h1></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Vote">
</form>
-->

not working yet

posts/templates/posts/index.html
{% extends "posts/base.html" %}
{% load static %}

{% block content %}
  {% if latest_post_list %}
    <ul>
      {% for post in latest_post_list %}
        {% include 'posts/timeline_post.html' %}
      {% endfor %}
    </ul>
  {% else %}
    <p>No posts are available.</p>
  {% endif %}
{% endblock %}

<!--

    {% load static %}
    <img src="{% static 'my_app/example.jpg' %}" alt="My image">

-->

posts/templates/posts/results.html
{% extends "posts/base.html" %}
{% load static %}

{% block title %}Post Details{% endblock %}

{% block content %}
  {% include 'posts/base_post.html' %}
{% endblock %}

posts/templates/posts/timeline_post.html
{% extends "posts/base_post.html" %}
{% load static %}

{% block media %}
    <a href="{% url 'posts:results' post.pk %}">
        {{ block.super }}
    </a>
{% endblock media %}


{% block buttons-left %}
    {{ block.super }}
    
    <a href="{% url 'posts:results' post.pk %}">
        <span class="material-icons">
            chat_bubble_outline
        </span>
    </a>
{% endblock buttons-left %}

{% block comments %}
<ul>
    {% for comment in post.comment_set.all|slice:"0:3" %}
    <li>
        <img class="profile-pic" src="{{ MEDIA_URL }}{{comment.user.profile_pic.url}}"><p class="comment"><strong>@{{comment.user}}</strong>{{ comment.comment_text }}</p>
    </li>
    {% endfor %}
</ul>
{% endblock comments %}


{% block postcomment-section %}
    {% if post.comment_set.count > 3 %}
        <a href="{% url 'posts:results' post.pk %}">
            <p>View all {{post.comment_set.count}} comments </p>
        </a>
    {% endif %}
{% endblock postcomment-section %}

templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>Auth</title>{% endblock %}
</head>
<body>
  {% block sidebar %}<!-- insert default navigation text for every page -->{% endblock %}
  {% block content %}<!-- default content text (typically empty) -->{% endblock %}
</body>
</html>